In [2]:
import matplotlib.pyplot as plt
import pandas as pd
import pylab as pl
import numpy as np
%matplotlib inline

In [3]:
covid = pd.read_csv('who_covid19.csv')

In [4]:
covid.head()

,Name,WHO Region,Cases - cumulative total,Cases - cumulative total per 100000 population,Cases - newly reported in last 7 days,Cases - newly reported in last 7 days per 100000 population,Cases - newly reported in last 24 hours,Deaths - cumulative total,Deaths - cumulative total per 100000 population,Deaths - newly reported in last 7 days,Deaths - newly reported in last 7 days per 100000 population,Deaths - newly reported in last 24 hours
0,Global,NaN,196553009,2521.675429,3999924,51.316996,623707,4200412,53.889156,63159,0.810298,10353
1,United States of America,Americas,34564448,10442.350000,471734,142.520000,90660,607095,183.410000,2155,0.650000,409
2,India,South-East Asia,31572344,2287.840000,279282,20.240000,44230,423217,30.670000,3747,0.270000,555
3,Brazil,Americas,19797086,9313.670000,323132,152.020000,48013,553179,260.250000,7575,3.560000,1344
4,Russian Federation,Europe,6242066,4277.310000,163544,112.070000,23564,157771,108.110000,5475,3.750000,794

In [5]:
covid.tail()

,Name,WHO Region,Cases - cumulative total,Cases - cumulative total per 100000 population,Cases - newly reported in last 7 days,Cases - newly reported in last 7 days per 100000 population,Cases - newly reported in last 24 hours,Deaths - cumulative total,Deaths - cumulative total per 100000 population,Deaths - newly reported in last 7 days,Deaths - newly reported in last 7 days per 100000 population,Deaths - newly reported in last 24 hours
233,Saint Helena,Africa,0,0.0,0,0.0,0,0,0.0,0,0.0,0
234,Tokelau,Western Pacific,0,0.0,0,0.0,0,0,0.0,0,0.0,0
235,Tonga,Western Pacific,0,0.0,0,0.0,0,0,0.0,0,0.0,0
236,Turkmenistan,Europe,0,0.0,0,0.0,0,0,0.0,0,0.0,0
237,Tuvalu,Western Pacific,0,0.0,0,0.0,0,0,0.0,0,0.0,0

In [6]:
covid.shape

(238, 12)

In [7]:
covid.columns

Index(['Name', 'WHO Region', 'Cases - cumulative total',
       'Cases - cumulative total per 100000 population',
       'Cases - newly reported in last 7 days',
       'Cases - newly reported in last 7 days per 100000 population',
       'Cases - newly reported in last 24 hours', 'Deaths - cumulative total',
       'Deaths - cumulative total per 100000 population',
       'Deaths - newly reported in last 7 days',
       'Deaths - newly reported in last 7 days per 100000 population',
       'Deaths - newly reported in last 24 hours'],
      dtype='object')

In [8]:
covid.dtypes

Name                                                             object
WHO Region                                                       object
Cases - cumulative total                                          int64
Cases - cumulative total per 100000 population                  float64
Cases - newly reported in last 7 days                             int64
Cases - newly reported in last 7 days per 100000 population     float64
Cases - newly reported in last 24 hours                           int64
Deaths - cumulative total                                         int64
Deaths - cumulative total per 100000 population                 float64
Deaths - newly reported in last 7 days                            int64
Deaths - newly reported in last 7 days per 100000 population    float64
Deaths - newly reported in last 24 hours                          int64
dtype: object

In [10]:
covid.describe()

,Cases - cumulative total,Cases - cumulative total per 100000 population,Cases - newly reported in last 7 days,Cases - newly reported in last 7 days per 100000 population,Cases - newly reported in last 24 hours,Deaths - cumulative total,Deaths - cumulative total per 100000 population,Deaths - newly reported in last 7 days,Deaths - newly reported in last 7 days per 100000 population,Deaths - newly reported in last 24 hours
count,2.380000e+02,237.000000,2.380000e+02,237.000000,238.000000,2.380000e+02,237.000000,238.000000,237.000000,238.000000
mean,1.651706e+06,3834.947955,3.361281e+04,87.918257,5241.235294,3.529758e+04,62.879574,530.747899,0.915951,87.000000
std,1.313683e+07,4170.716536,2.636535e+05,177.635033,41237.898952,2.790398e+05,82.093938,4214.571775,2.362335,690.382906
min,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000
25%,5.014750e+03,277.650000,3.650000e+01,2.670000,0.000000,4.425000e+01,2.940000,0.000000,0.000000,0.000000
50%,5.182250e+04,2287.840000,8.175000e+02,28.900000,72.000000,8.445000e+02,26.370000,5.500000,0.120000,0.000000
75%,3.774782e+05,6671.150000,5.827750e+03,95.540000,827.500000,6.413500e+03,98.010000,70.750000,0.790000,10.000000
max,1.965530e+08,18967.190000,3.999924e+06,1778.150000,623707.000000,4.200412e+06,594.860000,63159.000000,26.460000,10353.000000

In [12]:
# checking for missing values
covid.isnull().sum()

Name                                                            0
WHO Region                                                      1
Cases - cumulative total                                        0
Cases - cumulative total per 100000 population                  1
Cases - newly reported in last 7 days                           0
Cases - newly reported in last 7 days per 100000 population     1
Cases - newly reported in last 24 hours                         0
Deaths - cumulative total                                       0
Deaths - cumulative total per 100000 population                 1
Deaths - newly reported in last 7 days                          0
Deaths - newly reported in last 7 days per 100000 population    1
Deaths - newly reported in last 24 hours                        0
dtype: int64

In [13]:
covid.isnull().mean()

Name                                                            0.000000
WHO Region                                                      0.004202
Cases - cumulative total                                        0.000000
Cases - cumulative total per 100000 population                  0.004202
Cases - newly reported in last 7 days                           0.000000
Cases - newly reported in last 7 days per 100000 population     0.004202
Cases - newly reported in last 24 hours                         0.000000
Deaths - cumulative total                                       0.000000
Deaths - cumulative total per 100000 population                 0.004202
Deaths - newly reported in last 7 days                          0.000000
Deaths - newly reported in last 7 days per 100000 population    0.004202
Deaths - newly reported in last 24 hours                        0.000000
dtype: float64